Remove `getopt` dependency.
Wrote an argument parser. Removing the `getopt` dependency.

diff --git a/barnctl b/barnctl
--- a/barnctl
+++ b/barnctl
@@ -1,15 +1,5 @@
 #!/bin/bash
 
-case "$OSTYPE" in
-    linux-gnu )
-        os=ubuntu
-        ;;
-    darwin* )
-        os=osx
-        export PATH=/usr/local/opt/gnu-getopt/bin:$PATH
-        ;;
-esac
-
 SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)
 
 barnctl_bash_resource() {
@@ -25,18 +15,17 @@ _barnctl_get_server() {
 }
 
 barnctl_command_bootstrap() {
-    local o_help o_fingerprint o_github o_repository o_branch o_user o_force=1
-    barnctl_parse_arguments bootstrap \
+    eval "$(barnctl_parse_arguments bootstrap \
         "h,help" \
-        "u,user:" \
         "f,force" \
+        "u,user:" \
         "p,fingerprint:" "G,github:" \
         "b,branch:" "r,repository:" \
-        -- "$@"
+        -- "$@")"
 
-    local server=${o_argv[0]}
-    if [[ -n "$o_user" ]]; then
-        server="$o_user@$server"
+    local server=${1:-}
+    if [[ ${#o_user[@]} -ne 0 ]]; then
+        server="${o_user[0]}@$server"
     fi
 
 #    local gpg_key=$(<"$o_gpg")
@@ -65,12 +54,11 @@ barnctl_command_bootstrap() {
 }
 
 barnctl_command_update() {
-    local o_help o_user
-    barnctl_parse_arguments update "h,help" "u,user:" -- "$@"
+    eval "$(barnctl_parse_arguments update "h,help" "u,user:" -- "$@")"
 
-    local server=${o_argv[0]}
-    if [[ -n "$o_user" ]]; then
-        server="$o_user@$server"
+    local server=${1:-}
+    if [[ ${#o_user[@]} -ne 0 ]]; then
+        server="${o_user[0]}@$server"
     fi
 
     _compile_script() {
@@ -87,29 +75,24 @@ barnctl_command_update() {
 }
 
 barnctl_command_prepare() {
-    local o_user
-    barnctl_parse_arguments prepare "h,help" "u,user:" -- "$@"
-    local server=${o_argv[0]}
-    if [[ -n "$o_user" ]]; then
-        server="$o_user@$server"
+    eval "$(barnctl_parse_arguments prepare "h,help" "u,user:" -- "$@")"
+    local server=${1:-}
+    if [[ ${#o_user[@]} -ne 0 ]]; then
+        server="${o_user[0]}@$server"
     fi
     barnctl_bash_resource barnctl_prepare | ssh "$server" bash
 }
 
 barnctl_command_run() {
-    local o_user
-    barnctl_parse_arguments run \
-        "h,help" \
-        "u,user:" \
-        -- "$@"
-    ssh "$(_barnctl_get_server "${o_argv[0]}" "$o_user")" sudo /usr/local/bin/barnyard
+    eval "$(barnctl_parse_arguments run "h,help" "u,user:" -- "$@")"
+    ssh "$(_barnctl_get_server "$@" "${o_user[0]}")" sudo /usr/local/bin/barnyard
 }
 
+# TODO Outgoing.
 barnctl_command_develop() {
-    local o_help
-    barnctl_parse_arguments develop "h,help" -- "$@"
+    eval "$(barnctl_parse_arguments develop "h,help" -- "$@")"
     local directory
-    [[ ${#o_argv[@]} -ne 0 ]] || abend develop_directory_required
+    [[ $# -ne 0 ]] || abend develop_directory_required
     directory=${o_argv[0]}
     [[ -d "$directory" ]] || abend develop_not_a_directory "$directory"
 }
@@ -144,15 +127,23 @@ barnctl_quotedoc() {
     })"
 }
 
-barnctl_parse_arguments() {
-    local usage=$1
-    shift
+barnctl_command_arguments() {
+    barnctl_parse_arguments arguments ",long:" "s,:" "a,array@" "v,value:" "f,flag" -- "$@"
+}
 
-    declare -a is_short
-    declare -a is_arged
-    declare -a is_long
-    declare -a opt_long
-    declare -a opt_short
+barnctl_argument_error() {
+    echo "$@"
+    exit 1
+}
+
+bash_parse_arguments() {
+    local error=$(printf %q "$1") context=$(printf %q "$2")
+    shift 2
+
+    declare -a argument_lookup
+    declare -a argument_properties
+
+    local regex short long kind variable default
 
     while :
     do
@@ -162,95 +153,170 @@ barnctl_parse_arguments() {
                 break
                 ;;
             *)
-                local regex='([a-zA-Z0-9]?),([^:]*)(:?)'
+                regex='^([a-zA-Z0-9]?),([^@:#]*)([@:#]?)(=.*)?$'
                 # TODO Eval arguments instead.
-                [[ $1 =~ $regex ]] || abend bad_parameter_argument "$1"
-                local short=${BASH_REMATCH[1]} long=${BASH_REMATCH[2]} arged_2=${BASH_REMATCH[3]}
-                local arged=1
-                if [[ -n $arged_2 ]]; then
-                    arged=0
-                fi
-                if [[ -n "$long" ]]; then
-                    is_long+=("--${long}")
-                    if [[ $arged -eq 0 ]]; then
-                        is_arged+=("--${long}")
-                        opt_long+=("${long}:")
-                    else
-                        opt_long+=("${long}")
-                    fi
+                [[ "$1" =~ $regex ]] || { echo bad_parameter_argument "$1"; return; }
+                short=${BASH_REMATCH[1]} long=${BASH_REMATCH[2]} kind=${BASH_REMATCH[3]} variable= default="${BASH_REMATCH[4]}"
+                [[ -z "$long" ]] && variable=o_$short || variable=o_$long
+                if [[ "$default" != '' ]]; then
+                    case x"$kind" in
+                        x )
+                            kind=flag
+                            [[ "${default:1}" =~ ^[0-1]$ ]] || { echo "$error $context boolean $(printf %q "$1")" && return; }
+                            echo "local $variable=${default:1}"
+                            ;;
+                        x\! )
+                            kind=toggle
+                            [[ "${default:1}" =~ ^[0-1]$ ]] || { echo "$error $context boolean $(printf %q "$1")" && return; }
+                            echo "local $variable=${default:1}"
+                            ;;
+                        x\# )
+                            kind=count
+                            [[ "${default:1}" =~ ^-?[0-9]+$ ]] || { echo "$error $context integer $(printf %q "$1")" && return; }
+                            echo "local $variable=${default:1}"
+                            ;;
+                        x: )
+                            kind=value
+                            echo "declare -a $variable=( $(printf %q "${default:1}") )"
+                            ;;
+                        x@ )
+                            { echo "$error $context no_defaults $(printf %q "$1")" && return; }
+                            ;;
+                    esac
                 else
-                    is_long+=("--")
+                    case x"$kind" in
+                        x )
+                            kind=flag
+                            echo "local $variable=1"
+                            ;;
+                        x\! )
+                            kind=toggle
+                            echo "local $variable=0"
+                            ;;
+                        x\# )
+                            kind=count
+                            echo "local $variable=0"
+                            ;;
+                        x: )
+                            kind=value
+                            echo "declare -a $variable"
+                            ;;
+                        x@ )
+                            kind=array
+                            echo "declare -a $variable"
+                            ;;
+                    esac
+                fi
+                argument_eval="kind=$kind variable=$variable"
+                if [[ -n "$long" ]]; then
+                    argument_lookup+=("--${long}")
+                    argument_properties+=("$argument_eval")
                 fi
                 if [[ -n "$short" ]]; then
-                    is_short+=("-${short}")
-                    if [[ $arged -eq 0 ]]; then
-                        is_arged+=("-${short}")
-                        opt_short+=("${short}:")
-                    else
-                        opt_short+=("${short}")
-                    fi
-                else
-                    is_short+=("-")
+                    argument_lookup+=("-${short}")
+                    argument_properties+=("$argument_eval")
                 fi
                 shift
                 ;;
         esac
     done
 
-    local parsed=$(getopt -a -n acrectl -o +"$(printf "%s" "${opt_short[@]}")" --long "$(IFS=,; echo "${opt_long[*]}")" -- "$@")
-    if [[ $? != 0 ]]; then
-        abend usage_$usage
-    fi
-    eval set -- "$parsed"
-
-    while :
+    # TODO What does getopt think of `-`?
+    declare -a args=( "$@" )
+    local i=0 j arged flag
+    while [[ $i -lt ${#args[@]} ]]
     do
-        case "$1" in
-            --)
-                shift
+        arged=1
+        case "${args[$i]}" in
+            -- )
+                let i=i+1
                 break
                 ;;
-            --help | -h)
-                acrectl_usage $usage
-                exit
+            --* )
+                regex='^(--[a-zA-Z0-9]*)(=.*)?$'
+                [[ "${args[$i]}" =~ $regex ]] || { echo "$error $context unknown $(printf %q "$1")"; return; }
+                long="${BASH_REMATCH[1]}"
+                if [[ -z "${BASH_REMATCH[2]}" ]]; then
+                    let i=i+1
+                else
+                    arged=0
+                    args[i]=${BASH_REMATCH[2]}
+                fi
+                flag="$long"
+                for (( j=0; j<${#argument_lookup[@]}; j++ )); do
+                    [[ ${argument_lookup[$j]} == "$long" ]] && break
+                done
+                if [[ $j -eq ${#argument_lookup[@]} ]]; then
+                    echo "$error unknown $(printf %q "$long")"
+                    break
+                fi
+                eval "${argument_properties[$j]}"
+                if [[ $kind == toggle && "$long" =~ no- ]]; then
+                    echo "$variable=0"
+                fi
+                ;;
+            -* )
+                short="${args[$i]}"
+                short="${short:0:2}"
+                flag="$short"
+                for (( j=0; j<${#argument_lookup[@]}; j++ )); do
+                    [[ ${argument_lookup[$j]} == "$short" ]] && break
+                done
+                if [[ $j -eq ${#argument_lookup[@]} ]]; then
+                    { echo "$error $context unknown $(printf %q "$short")"; return; }
+                fi
+                eval "${argument_properties[$j]}"
+                case "$kind" in
+                    array | value )
+                        args[i]=${short:2}
+                        ;;
+                    * )
+                        # TODO If you have args a b and c and you get -abd what
+                        # does getopt do? Seems to just append...
+                        if [[ ${#args[i]} -gt 2 ]]; then
+                            args[i]="-${short:2}"
+                        else
+                            let i=i+1
+                        fi
+                        ;;
+                esac
                 ;;
             *)
-                local arged=1 variable
-                if [[ " ${is_arged[@]} " == *" ${1} "* ]]; then
-                    arged=0
-                fi
-                if [[ "${1:0:2}" == "--" ]]; then
-                    variable="o_${1:2:${#1}}"
-                else
-                    local index=0
-                    for (( index=0; index<=${#is_short[@]}; index++ )); do
-                        [[ ${is_short[$index]} == $1 ]] && break
-                    done
-                    if [[ "${is_long[$index]}" != "--" ]]; then
-                        local long=${is_long[$index]}
-                        variable="o_${long:2:${#long}}"
-                    else
-                        variable="o_${1:1:${#1}}"
-                    fi
-                fi
-                local value=
-                shift
-                if [[ $arged == 0 ]]; then
-                    value=$1
-                    shift
-                else
-                    value=0
-                fi
-                eval "$variable=\$value"
+                break
+                ;;
+        esac
+        case "$kind" in
+            flag | count | toggle )
+                [[ $arged -eq 0 ]] && { echo "$error $context no_args $(printf %q "$flag")"; return; }
+                ;;
+        esac
+        case "$kind" in
+            flag )
+                echo "$variable=0"
+                ;;
+            count )
+                echo "let $variable=$variable+1"
+                ;;
+            toggle )
+                echo "[[ \$$variable -eq 0 ]] && $variable=1 || variable=0"
+                ;;
+            value )
+                echo "$variable[0]=$(printf %q "${args[$i]}")"
+                let i=i+1
+                ;;
+            array )
+                echo "$variable[0]+=($(printf %q "${args[$i]}"))"
+                let i=i+1
                 ;;
         esac
     done
 
-    o_argv=()
-    while [[ $# -ne 0 ]]; do
-        o_argv+=("$1")
-        shift
-    done
+    [[ $i -eq ${#args[@]} ]] && echo "set --" || echo "set --$(printf ' %q' "${args[@]:$i}")"
+}
+
+barnctl_parse_arguments() {
+    bash_parse_arguments barnctl_argument_error "$@"
+    echo "[[ \$o_help -eq 0 ]] && usage_$1"
 }
 
 IFS=$'\n' read -d '' -r -a BARNCTL_COMMANDS < <( \
@@ -268,8 +334,12 @@ barnctl_next_command() {
     done
 }
 
-barnctl_parse_arguments root "a,alpha:" "h,help" -- "$@"
-barnctl_next_command "" "${o_argv[@]}"
+main() {
+    eval "$(barnctl_parse_arguments root "h,help" -- "$@")"
+    barnctl_next_command "" "$@"
+}
+
+main "$@"
 
 exit
 
